language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm api sh -c "python3 manage.py wait_for_db && python3 manage.py test"
